#!/usr/bin/env node
// LapViewer live repo-state snapshot for agents.
// Runs as a Cursor `sessionStart` hook and can be run manually from the repo root:
//   node .cursor/hooks/project-state.mjs
//
// Side effects (reliable): writes docs/agents/PROJECT_STATE.generated.md.
// Stdout (future-proof): prints { additional_context } per the sessionStart schema.
//   NOTE: as of this writing Cursor drops sessionStart additional_context due to a
//   known race (only `env` is reliable), so agents should READ the generated file.
// Fail-open by design: any error still exits 0 so a session is never blocked.

import { execSync } from "node:child_process";
import { writeFileSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

function git(args) {
  try {
    return execSync(`git ${args}`, {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    return "";
  }
}

function detectScripts() {
  try {
    const pkg = JSON.parse(readFileSync(resolve("package.json"), "utf8"));
    const scripts = pkg.scripts ?? {};
    const row = (name) => {
      const cmd = scripts[name];
      if (!cmd || /no test specified/i.test(cmd)) return `- \`npm run ${name}\`: not available`;
      return `- \`npm run ${name}\`: ${cmd}`;
    };
    return ["check", "test", "build"].map(row).join("\n");
  } catch {
    return "- unknown (no package.json at repo root)";
  }
}

const branch = git("branch --show-current");
const statusSb = (git("status -sb").split("\n")[0] ?? "").trim();
const remotes = git("remote -v");
const recent = git("log --oneline -5");
const verification = detectScripts();
const generatedAt = new Date().toISOString();

const remoteBlock = remotes || "none configured (work locally; ask before adding one)";

const body = `<!-- GENERATED by \`node .cursor/hooks/project-state.mjs\` (sessionStart hook). Do not edit by hand. -->
# Project state (generated)

_Generated: ${generatedAt}_

## Git
- **Current branch:** ${branch || "(detached or unknown)"}
- **Status / ahead-behind:** ${statusSb || "(unknown)"}
- **Remotes:**
\`\`\`
${remoteBlock}
\`\`\`

## Recent commits
\`\`\`
${recent || "(none)"}
\`\`\`

## Verification commands (from root package.json)
${verification}

---
_Facts here are derived at runtime. Re-run \`npm run project:state\` (or the hook) if this looks stale._
`;

try {
  writeFileSync(resolve("docs/agents/PROJECT_STATE.generated.md"), body, "utf8");
} catch {
  // best-effort; never block the session
}

const additional_context = [
  "LapViewer live repo state (sessionStart hook — ground truth, do not assume from docs):",
  `- branch: ${branch || "unknown"}`,
  `- status: ${statusSb || "unknown"}`,
  `- remotes: ${remotes ? remotes.replace(/\s*\n\s*/g, " | ") : "NONE configured"}`,
  `- verification: check/test/build availability in docs/agents/PROJECT_STATE.generated.md`,
].join("\n");

process.stdout.write(JSON.stringify({ additional_context }));
process.exit(0);
